CREATE DATABASE gstok;
USE gstok;

GRANT select, insert, update, delete
ON gstok.*
TO gstok_user@localhost identified by 'gs_p@$$*!';


CREATE TABLE FUNCIONARIO(
	CPF BIGINT(11) NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	SENHA VARCHAR(50) NOT NULL,
	GERENTE INT(1) NOT NULL DEFAULT 0,
    ATIVO INT(1) NOT NULL DEFAULT 1,
	PRIMARY KEY(CPF)
);

INSERT INTO FUNCIONARIO (CPF, NOME, SENHA, GERENTE)
    VALUES
        (11111111111, 'Gerente', '12345678', 1),
        (22222222222, 'Funcionário', '12345678', 0);

CREATE TABLE CLIENTE(
	CPF INT(11) NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	TELEFONE VARCHAR(11) NOT NULL,
	PRIMARY KEY(CPF)
);

CREATE TABLE MARCA(
	COD_MARCA INT(5) NOT NULL AUTO_INCREMENT,
	DESC_MARCA VARCHAR(60) NOT NULL UNIQUE,
	PRIMARY KEY(COD_MARCA)
);

CREATE TABLE CATEGORIA(
	COD_CATEGORIA INT(5) NOT NULL AUTO_INCREMENT,
	DESC_CATEGORIA VARCHAR(60) NOT NULL UNIQUE,
	PRIMARY KEY(COD_CATEGORIA)
);


CREATE TABLE PRODUTO(
	ID INT(5) NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(40) NOT NULL,
	DESCRICAO VARCHAR(60),
	COD_BARRAS INT(12) NOT NULL UNIQUE,
	PRECO FLOAT NOT NULL,
    COD_CATEGORIA INT(5) NOT NULL,
	COD_MARCA INT(5) NOT NULL,
	QUANTIDADE INT(4) NOT NULL,
	LIMITE_MIN INT(4) NOT NULL,
	LIMITE_MAX INT(4) NOT NULL,
	CPF_GERENTE BIGINT(11) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(COD_MARCA) REFERENCES MARCA(COD_MARCA),
    FOREIGN KEY(COD_CATEGORIA) REFERENCES CATEGORIA(COD_CATEGORIA),
	FOREIGN KEY(CPF_GERENTE) REFERENCES FUNCIONARIO(CPF)
);

CREATE TABLE VENDA(
    ID INT(5) NOT NULL,
    ID_PRODUTO INT(5) NOT NULL,
    CPF_FUNC BIGINT(11) NOT NULL,
    CPF_CLIENTE BIGINT(11) NOT NULL,
    QUANTIDADE INT(3) NOT NULL,
    DATA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID,ID_PRODUTO),
    FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID),
    FOREIGN KEY(CPF_FUNC) REFERENCES FUNCIONARIO(CPF),
    FOREIGN KEY(CPF_CLIENTE) REFERENCES CLIENTE(CPF)
);
    


