CREATE DATABASE gstok
USE gstok

GRANT select, insert, update, delete
ON gstok.*
TO gstok_user@localhost identified by 'gs_p@$$*!';

CREATE TIPO(
	COD_TIPO INT(2) NOT NULL,
	DESC_TIPO VARCHAR(50) NOT NULL,
	PRIMARY KEY(COD_TIPO)
);

CREATE FUNCIONARIO(
	CPF INT(11) NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	COD_TIPO INT(2) NOT NULL,
	PRIMARY KEY(CPF),
	FOREIGN KEY(COD_TIPO) REFERENCES TIPO(COD_TIPO)
);

CREATE TABLE MARCA(
	COD_MARCA INT(5) NOT NULL AUTO_INCREMENT,
	DESC_MARCA VARCHAR(60) NOT NULL,
	PRIMARY KEY(COD_MARCA)
);

CREATE TABLE PRODUTO(
	ID INT(5) NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(40) NOT NULL,
	DESCRICAO VARCHAR(60),
	COD_BARRAS INT(12) NOT NULL UNIQUE,
	PRECO_UNI FLOAT(4,2) NOT NULL,
	COD_MARCA INT(5) NOT NULL,
	QUANTIDADE INT(4) NOT NULL
	LIMITE_MIN INT(4) NOT NULL,
	LIMET_MAX INT(4) NOT NULL,
	CPF_FUNC INT(11) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(COD_MARCA) REFERENCES MARCA(COD_MARCA),
	FOREIGN KEY(CPF_FUNC) REFERENCES FUNCIONARIO(CPF)
);

CREATE TABLE LOTE(
	ID_PROD INT(5) NOT NULL,
	PRECO FLOAT(4,2) NOT NULL,
	QUANTIDADE INT (3) NOT NULL,
	PRIMARY KEY(ID_PROD),
	FOREIGN KEY (ID_PROD) REFERENCES PRODUTO(ID)
);


